workflows:
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        labels:
          - ${PACKAGE_NAME}
        environment:
          android_signing:
            - testKeystore
          groups:
            - firebase_credentials
            - google_play_credentials2
            - module_credentials
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic10"
            GOOGLE_PLAY_TRACK: internal
        triggering:
          events:
              #- pull_request 
              - push
          # branch_patterns:
          # - pattern: "main"
          #   include: true
          #   source: false
        scripts:
          - name: Set up local.properties
            script: |
              echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          - name: Get Flutter packages
            script: |
              flutter packages pub get
          - name: Build aab
            script: | 
                flutter build appbundle

          - name: Build AAB with Flutter
            script: |
              LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
              if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
              else
                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
              fi
              flutter build appbundle --release \
                --build-name=1.0.$UPDATED_BUILD_NUMBER \
                --build-number=$UPDATED_BUILD_NUMBER
        artifacts:
          - build/**/outputs/**/*.aab
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          google_play:
            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS2
            track: internal
            submit_as_draft: true